---
- name: Monitoramento
  hosts: webservers
  become: true
  tasks:    
    - name: Instalar Prometheus
      apt:
        name: prometheus
        state: present    

    - name: repositório Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Adicionar o repositório
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present
    
    - name: Reiniciar o serviço Prometheus
      service:
        name: prometheus
        state: restarted
    
    - name: Reiniciar o serviço Grafana
      service:
        name: grafana-server
        state: restarted
