---
- name: Instalação de pacotes
  hosts: webservers
  become: yes

  tasks:
    - name: Atualizar Pacotes
      apt:
        update_cache: yes

    - name: Instalar Git
      apt:
        name: git
        state: present

    - name: Instalar Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: repositório Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Instalar Docker Compose
      apt:
        name: docker-compose
        state: present
